# NumPy Exercises

## Importing Library

In [117]:
import numpy as np

## Create a vector of size 10.
   ### Fill all the elements with zeros, print the result
   ### Assign a value of “1” to the fifth value in this vector. Print the result.

In [118]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
a.fill(0)
print(a)
a[4] = 1
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


## Create a vector with values ranging from 1 to 20 inclusive
   ### Print the result
   ### Reverse the vector then print the result

In [119]:
b = np.arange(1,21)
print(b)
b = b[::-1]
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


## Create a random vector of size 50.
   ### Print the vector
   ### Find the mean of the vector and print the result

In [120]:
c = np.random.randint(0,101,50)
print(c)
c_mean = c.mean()
print(c_mean)

[63 68 13 27 76  5 19 72 40 55 97 51 83 20 21 97 54 74 84 10 18 67 76 98
  1 30 74  8 21 24 51 25 83 77 97  4 11 10 17 24 91 63 42 83 83 65 35 18
 22 40]
47.74


## Create a 3x4 matrix with a value of “1” for each element. Print the result.
   ### Create a 4x2 matrix with a value of “1” for each element, print the result.
   ### Multiply both 3x4 and 4x3 matrix and print the final result

In [121]:
d = np.full((3, 4), 1)
print(d)
d_2 = np.full((4, 2), 1)
print(d_2)
d_result = d.dot(d_2)
print(d_result)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[[4 4]
 [4 4]
 [4 4]]


## Create a 5x5 array with random numbers, print the array
   ### Find the min value from this array, print the result
   ### Find the max value from this array, print the result

In [122]:
e =  np.random.randint(0,100,size=(5,5))
print(e)
print(e.min())
print(e.max())

[[25 78 42  1 29]
 [27 74 89  0 34]
 [84 33 44 91  0]
 [79  9 48 58 94]
 [42 32 13 52  1]]
0
94


# Pandas Exercises

# Importing Library

In [123]:
import pandas as pd

##
   ### Create a Panda Series from 10 to 50 in multiples of 10. Print the series.
   ### Create a dictionary of weekdays and print this as panda series.
   ### Example {“Monday”:1, “Tuesday:2 etc..}
   ### Create a data frame in Pandas with Months of the calendar year.

   ### Your output should appear like this

   ### Name         Month

   ### January         1

   ### February        2

   ### March           3

   ### ….              ..

   ### ….              ..

In [124]:
a = pd.Series(np.arange(10,51,step=10))
print(a)
a_weekdays = pd.Series({"Monday":1 , "Tuesday":2,"Wednesday":3,"Thursday":4,"Friday":5,"Saturday":6,"Sunday":7})
print(a_weekdays)
a_months = pd.DataFrame({'Name':['January', 'February','March',
                                 'April', 'May','June', 'July',
                                 'August', 'September','October',
                                 'November','December'],
                         'Month':[1,2,3,4,5,6,7,8,9,10,11,12]})
print(a_months.to_string(index=False))

0    10
1    20
2    30
3    40
4    50
dtype: int32
Monday       1
Tuesday      2
Wednesday    3
Thursday     4
Friday       5
Saturday     6
Sunday       7
dtype: int64
     Name  Month
  January      1
 February      2
    March      3
    April      4
      May      5
     June      6
     July      7
   August      8
September      9
  October     10
 November     11
 December     12


## Use this input data and create a dataframe. Print the dataframe

   ### input = [{'Name':'Monday', 'day':1},

   ###        {'Name':'Tuesday', 'day':2},

   ###        {'Name':'Wednesday', 'day':3},

   ###        {'Name':'Thursday', 'day':4},

   ###        {'Name':'Friday', 'day':5},

   ###        {'Name':'Saturday', 'day':6},

   ###        {'Name':'Sunday', 'day':7},

   ###        ]

   ### Next, iterate over this data frame and print the results.

In [125]:
b = pd.DataFrame( [{'Name':'Monday', 'day':1},

                   {'Name':'Tuesday', 'day':2},

                   {'Name':'Wednesday', 'day':3},

                   {'Name':'Thursday', 'day':4},

                   {'Name':'Friday', 'day':5},

                   {'Name':'Saturday', 'day':6},

                   {'Name':'Sunday', 'day':7},

                   ])
print(b.to_string(index=False))
for col, data in b.items():
    print('{}{}'.format(col,''), '{}{}'.format(data, ''))

     Name  day
   Monday    1
  Tuesday    2
Wednesday    3
 Thursday    4
   Friday    5
 Saturday    6
   Sunday    7
Name 0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
Name: Name, dtype: object
day 0    1
1    2
2    3
3    4
4    5
5    6
6    7
Name: day, dtype: int64


## Create a numpy array with 5 elements of your choice. Index these elements in Panda series and print the series.

In [126]:
c = np.array(['Tuesday','Friday','Saturday','Monday','Sunday'])
c_series = a_weekdays.loc[c]
print(c_series)

Tuesday     2
Friday      5
Saturday    6
Monday      1
Sunday      7
dtype: int64
